CREATE TABLE IF NOT EXISTS users(
login TEXT NOT NULL,
password TEXT NOT NULL,
date_reg TEXT NOT NULL,
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);

CREATE TABLE IF NOT EXISTS posts(
title TEXT NOT NULL,
content TEXT NOT NULL,
author TEXT NOT NULL,
tag TEXT DEFAULT 'Без тега',
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
)